# Generated by Django 4.2 on 2023-04-28 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='adverster',
            new_name='advertiser',
        ),
    ]
