# Generated by Django 4.2 on 2023-04-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_rename_adverster_ad_advertiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ad',
            name='impression_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
